<a href="https://colab.research.google.com/github/vbddinho/puc_minas_machine/blob/main/plano3.ipvisitantenb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Definição de configurações de dataframes
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.set_option('display.precision', 4)
pd.set_option('display.expand_frame_repr', False)

In [4]:
#Configurando os plots para serem emandanteibidos diretamente no notebook
%matplotlib inline

In [5]:
df_jogos = pd.read_csv('dados/campeonato-brasileiro-full.csv',sep=',',encoding = "UTF-8")
df_estatisticas = pd.read_csv('dados/campeonato-brasileiro-estatisticas-full.csv', sep=',',encoding = "UTF-8")

In [6]:
df_jogos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8025 entries, 0 to 8024
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ID                  8025 non-null   int64
 1   rodata              8025 non-null   int64
 2   data                8025 non-null   object
 3   hora                8025 non-null   object
 4   mandante            8025 non-null   object
 5   visitante           8025 non-null   object
 6   formacao_mandante   3051 non-null   object
 7   formacao_visitante  3051 non-null   object
 8   tecnico_mandante    3415 non-null   object
 9   tecnico_visitante   3415 non-null   object
 10  vencedor            8025 non-null   object
 11  arena               8025 non-null   object
 12  mandante_Placar     8025 non-null   int64
 13  visitante_Placar    8025 non-null   int64
 14  mandante_Estado     8025 non-null   object
 15  visitante_Estado    8025 non-null   object
dtypes: int64(4), object(12)
memory usage: 1003.2+ KB

In [7]:
df_jogos.rename(columns={'ID':'partida_id'},inplace=True)
df_jogos.rename(columns={'rodata':'rodada'},inplace=True)
df_jogos.drop(columns=['hora','arena','visitante_Estado','mandante_Estado','tecnico_mandante','tecnico_visitante'],inplace=True)

In [8]:
df_estatisticas.tail()

       partida_id  rodata          clube  chutes  chutes_no_alvo posse_de_bola  passes precisao_passes  faltas  cartao_amarelo  cartao_vermelho  impedimentos  escanteios
16045        8023      38    Atletico-MG      17               7           41%     351             82%      19               6                0             0           4
16046        8024      38  Internacional      15               8           48%     287             77%      13               2                0             1           6
16047        8024      38      Palmeiras      11               2           52%     306             82%      17               3                0             2           5
16048        8025      38          Goias       6               2           35%     330             80%      12               2                0             1           3
16049        8025      38      Sao Paulo      13               7           65%     591             90%      14               1                0             0           4

In [9]:
df_jogos.tail()

      partida_id  rodada        data       mandante    visitante formacao_mandante formacao_visitante       vencedor  mandante_Placar  visitante_Placar
8020        8021      38  13/11/2022         Cuiaba     Coritiba           4-1-4-1            4-1-4-1         Cuiaba                2                 1
8021        8022      38  13/11/2022     Bragantino   Fluminense           4-2-3-1            4-2-3-1     Fluminense                0                 1
8022        8023      38  13/11/2022    Corinthians  Atletico-MG           4-1-4-1            4-2-3-1    Atletico-MG                0                 1
8023        8024      38  13/11/2022  Internacional    Palmeiras           4-2-3-1            4-2-3-1  Internacional                3                 0
8024        8025      38  13/11/2022          Goias    Sao Paulo           4-2-3-1          4-1-2-1-2      Sao Paulo                0                 4

In [10]:
#Fonte https://pt.stackoverflow.com/questions/484866/como-preencher-uma-coluna-de-um-df-pandas-usando-como-compara%C3%A7%C3%A3o-uma-coluna-es
df_jogos = pd.merge(df_jogos,df_estatisticas,how='left',right_on=['partida_id','clube'],left_on=['partida_id','mandante'])
df_jogos = pd.merge(df_jogos,df_estatisticas,how='left',right_on=['partida_id','clube'],left_on=['partida_id','visitante'])

In [11]:
df_jogos.columns

Index(['partida_id', 'rodada', 'data', 'mandante', 'visitante', 'formacao_mandante', 'formacao_visitante', 'vencedor', 'mandante_Placar', 'visitante_Placar', 'rodata_x', 'clube_x', 'chutes_x', 'chutes_no_alvo_x', 'posse_de_bola_x', 'passes_x', 'precisao_passes_x', 'faltas_x', 'cartao_amarelo_x', 'cartao_vermelho_x', 'impedimentos_x', 'escanteios_x', 'rodata_y', 'clube_y', 'chutes_y', 'chutes_no_alvo_y', 'posse_de_bola_y', 'passes_y', 'precisao_passes_y', 'faltas_y', 'cartao_amarelo_y', 'cartao_vermelho_y', 'impedimentos_y', 'escanteios_y'], dtype='object')

In [12]:
df_jogos.columns = ['partida_id', 'rodada', 'data', 'mandante', 'visitante', 'formacao_mandante', 'formacao_visitante', 'vencedor', 'mandante_placar', 'visitante_placar', 'rodata_mandante', 'clube_mandante', 'chutes_mandante', 'chutes_no_alvo_mandante', 'posse_de_bola_mandante', 'passes_mandante', 'precisao_passes_mandante', 'faltas_mandante', 'cartao_amarelo_mandante', 'cartao_vermelho_mandante', 'impedimentos_mandante', 'escanteios_mandante', 'rodata_visitante', 'clube_visitante', 'chutes_visitante', 'chutes_no_alvo_visitante', 'posse_de_bola_visitante', 'passes_visitante', 'precisao_passes_visitante', 'faltas_visitante', 'cartao_amarelo_visitante', 'cartao_vermelho_visitante', 'impedimentos_visitante', 'escanteios_visitante']

In [13]:
df_jogos.drop(columns=['rodata_mandante','mandante','visitante','rodata_visitante'],inplace=True)

In [14]:
df_jogos.tail()

      partida_id  rodada        data formacao_mandante formacao_visitante       vencedor  mandante_placar  visitante_placar clube_mandante  chutes_mandante  chutes_no_alvo_mandante posse_de_bola_mandante  passes_mandante precisao_passes_mandante  faltas_mandante  cartao_amarelo_mandante  cartao_vermelho_mandante  impedimentos_mandante  escanteios_mandante clube_visitante  chutes_visitante  chutes_no_alvo_visitante posse_de_bola_visitante  passes_visitante precisao_passes_visitante  faltas_visitante  cartao_amarelo_visitante  cartao_vermelho_visitante  impedimentos_visitante  escanteios_visitante
8020        8021      38  13/11/2022           4-1-4-1            4-1-4-1         Cuiaba                2                 1         Cuiaba               17                        8                    57%              505                      88%                9                        1                         0                      2                    8        Coritiba                 4                         2                     43%               389                       82%                 8                         3                          1                       2                     1
8021        8022      38  13/11/2022           4-2-3-1            4-2-3-1     Fluminense                0                 1     Bragantino               13                        4                    41%              319                      77%               16                        3                         0                      5                    4      Fluminense                 8                         4                     59%               463                       82%                15                         2                          0                       0                     9
8022        8023      38  13/11/2022           4-1-4-1            4-2-3-1    Atletico-MG                0                 1    Corinthians               17                        4                    59%              494                      84%               11                        3                         0                      1                    5     Atletico-MG                17                         7                     41%               351                       82%                19                         6                          0                       0                     4
8023        8024      38  13/11/2022           4-2-3-1            4-2-3-1  Internacional                3                 0  Internacional               15                        8                    48%              287                      77%               13                        2                         0                      1                    6       Palmeiras                11                         2                     52%               306                       82%                17                         3                          0                       2                     5
8024        8025      38  13/11/2022           4-2-3-1          4-1-2-1-2      Sao Paulo                0                 4          Goias                6                        2                    35%              330                      80%               12                        2                         0                      1                    3       Sao Paulo                13                         7                     65%               591                       90%                14                         1                          0                       0                     4

In [15]:
#Converte a data do tipo objeto para o tipo datetime e cria a coluna ano
df_jogos["data"] = pd.to_datetime(df_jogos["data"],format='%d/%m/%Y',dayfirst=True)
df_jogos["ano"] = df_jogos["data"].dt.year

In [16]:
#temporada de 2020 e 2021 foi afetada pelo COVID-19, realizando ajuste
df_jogos.loc[(df_jogos["data"]>="2020/08/08") & (df_jogos["data"]<="2021/02/25"),"ano" ] = 2020
df_jogos.loc[(df_jogos["data"]>="2021/05/29") & (df_jogos["data"]<="2021/12/09"),"ano" ] = 2021
df_jogos.rename(columns={'ano':'temporada'},inplace=True)

In [17]:
df_jogos.shape

(8025, 31)

In [19]:
df = df_jogos[df_jogos['temporada']>=2018]

df_jogos[df_jogos['temporada']>=2018].isna().sum()

partida_id                   0
rodada                       0
data                         0
formacao_mandante            0
formacao_visitante           0
vencedor                     0
mandante_placar              0
visitante_placar             0
clube_mandante               0
chutes_mandante              0
chutes_no_alvo_mandante      0
posse_de_bola_mandante       0
passes_mandante              0
precisao_passes_mandante     0
faltas_mandante              0
cartao_amarelo_mandante      0
cartao_vermelho_mandante     0
impedimentos_mandante        0
escanteios_mandante          0
clube_visitante              0
chutes_visitante             0
chutes_no_alvo_visitante     0
posse_de_bola_visitante      0
passes_visitante             0
precisao_passes_visitante    0
faltas_visitante             0
cartao_amarelo_visitante     0
cartao_vermelho_visitante    0
impedimentos_visitante       0
escanteios_visitante         0
temporada                    0
dtype: int64

In [22]:
df.tail()

      partida_id  rodada       data formacao_mandante formacao_visitante       vencedor  mandante_placar  visitante_placar clube_mandante  chutes_mandante  chutes_no_alvo_mandante posse_de_bola_mandante  passes_mandante precisao_passes_mandante  faltas_mandante  cartao_amarelo_mandante  cartao_vermelho_mandante  impedimentos_mandante  escanteios_mandante clube_visitante  chutes_visitante  chutes_no_alvo_visitante posse_de_bola_visitante  passes_visitante precisao_passes_visitante  faltas_visitante  cartao_amarelo_visitante  cartao_vermelho_visitante  impedimentos_visitante  escanteios_visitante  temporada  mandante_win  visitante_win empate
8020        8021      38 2022-11-13           4-1-4-1            4-1-4-1         Cuiaba                2                 1         Cuiaba               17                        8                    57%              505                      88%                9                        1                         0                      2                    8        Coritiba                 4                         2                     43%               389                       82%                 8                         3                          1                       2                     1       2022           1.0            NaN    NaN
8021        8022      38 2022-11-13           4-2-3-1            4-2-3-1     Fluminense                0                 1     Bragantino               13                        4                    41%              319                      77%               16                        3                         0                      5                    4      Fluminense                 8                         4                     59%               463                       82%                15                         2                          0                       0                     9       2022           NaN            1.0    NaN
8022        8023      38 2022-11-13           4-1-4-1            4-2-3-1    Atletico-MG                0                 1    Corinthians               17                        4                    59%              494                      84%               11                        3                         0                      1                    5     Atletico-MG                17                         7                     41%               351                       82%                19                         6                          0                       0                     4       2022           NaN            1.0    NaN
8023        8024      38 2022-11-13           4-2-3-1            4-2-3-1  Internacional                3                 0  Internacional               15                        8                    48%              287                      77%               13                        2                         0                      1                    6       Palmeiras                11                         2                     52%               306                       82%                17                         3                          0                       2                     5       2022           1.0            NaN    NaN
8024        8025      38 2022-11-13           4-2-3-1          4-1-2-1-2      Sao Paulo                0                 4          Goias                6                        2                    35%              330                      80%               12                        2                         0                      1                    3       Sao Paulo                13                         7                     65%               591                       90%                14                         1                          0                       0                     4       2022           NaN            1.0    NaN

In [21]:
df.loc[(df['vencedor']==df['clube_mandante']),'mandante_win'] = 1
df.loc[(df['vencedor']==df['clube_visitante']),'visitante_win'] = 1
df.loc[(df['vencedor']=='-'),'empate'] = '1'

C:\Users\ADM\AppData\Local\Temp\ipykernel_17064\4083114983.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['vencedor']==df['clube_mandante']),'mandante_win'] = 1
C:\Users\ADM\AppData\Local\Temp\ipykernel_17064\4083114983.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['vencedor']==df['clube_visitante']),'visitante_win'] = 1
C:\Users\ADM\AppData\Local\Temp\ipykernel_17064\4083114983.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[(df['vencedor']=='-'),'empate'] = '1'

In [27]:
df['mandante_win'].fillna(value=0, inplace=True)
df['visitante_win'].fillna(value=0, inplace=True)
df['empate'].fillna(value=0, inplace=True)

C:\Users\ADM\AppData\Local\Temp\ipykernel_17064\2124758790.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mandante_win'].fillna(value=0, inplace=True)
C:\Users\ADM\AppData\Local\Temp\ipykernel_17064\2124758790.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['visitante_win'].fillna(value=0, inplace=True)
C:\Users\ADM\AppData\Local\Temp\ipykernel_17064\2124758790.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['empate'].fillna(value=0, inplace=True)

In [32]:
df.shape

(1900, 34)

In [33]:
df.tail()

      partida_id  rodada       data formacao_mandante formacao_visitante       vencedor  mandante_placar  visitante_placar clube_mandante  chutes_mandante  chutes_no_alvo_mandante posse_de_bola_mandante  passes_mandante precisao_passes_mandante  faltas_mandante  cartao_amarelo_mandante  cartao_vermelho_mandante  impedimentos_mandante  escanteios_mandante clube_visitante  chutes_visitante  chutes_no_alvo_visitante posse_de_bola_visitante  passes_visitante precisao_passes_visitante  faltas_visitante  cartao_amarelo_visitante  cartao_vermelho_visitante  impedimentos_visitante  escanteios_visitante  temporada  mandante_win  visitante_win empate
8020        8021      38 2022-11-13           4-1-4-1            4-1-4-1         Cuiaba                2                 1         Cuiaba               17                        8                    57%              505                      88%                9                        1                         0                      2                    8        Coritiba                 4                         2                     43%               389                       82%                 8                         3                          1                       2                     1       2022           1.0            0.0      0
8021        8022      38 2022-11-13           4-2-3-1            4-2-3-1     Fluminense                0                 1     Bragantino               13                        4                    41%              319                      77%               16                        3                         0                      5                    4      Fluminense                 8                         4                     59%               463                       82%                15                         2                          0                       0                     9       2022           0.0            1.0      0
8022        8023      38 2022-11-13           4-1-4-1            4-2-3-1    Atletico-MG                0                 1    Corinthians               17                        4                    59%              494                      84%               11                        3                         0                      1                    5     Atletico-MG                17                         7                     41%               351                       82%                19                         6                          0                       0                     4       2022           0.0            1.0      0
8023        8024      38 2022-11-13           4-2-3-1            4-2-3-1  Internacional                3                 0  Internacional               15                        8                    48%              287                      77%               13                        2                         0                      1                    6       Palmeiras                11                         2                     52%               306                       82%                17                         3                          0                       2                     5       2022           1.0            0.0      0
8024        8025      38 2022-11-13           4-2-3-1          4-1-2-1-2      Sao Paulo                0                 4          Goias                6                        2                    35%              330                      80%               12                        2                         0                      1                    3       Sao Paulo                13                         7                     65%               591                       90%                14                         1                          0                       0                     4       2022           0.0            1.0      0

In [42]:
#df2018_2022.groupby([df2018_2022['resultado'], df2018_2022['mv']]).agg({'partida_id': 'count'})
#df.groupby([df['temporada']]).agg({ 'mandante_win':'sum'})
df[(df)].groupby([df['temporada']]).agg({ 'visitante_win':'sum'})
#df.groupby([df['temporada']]).agg({ 'empate':'sum'})

               visitante_win
vencedor
-                        0.0
America-MG              12.0
Athletico-PR            24.0
Atletico-GO             15.0
Atletico-MG             30.0
Avai                     4.0
Bahia                   13.0
Botafogo-RJ             18.0
Bragantino              13.0
CSA                      2.0
Ceara                   16.0
Chapecoense              5.0
Corinthians             22.0
Coritiba                 4.0
Cruzeiro                 5.0
Cuiaba                   7.0
Flamengo                43.0
Fluminense              29.0
Fortaleza               20.0
Goias                   12.0
Gremio                  21.0
Internacional           29.0
Juventude                3.0
Palmeiras               40.0
Parana                   1.0
Santos                  24.0
Sao Paulo               30.0
Sport                   11.0
Vasco                    9.0
Vitoria                  2.0